routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/drilldown', 'Admin\HomeController@drilldown')->name('dash');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

    //change password
    Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
    Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');
    
    // settings
    Route::resource('settings', 'Admin\SettingsController');
    // Route::group(['namespace' => 'Inventory'], function () {
        
        includeRouteFiles(__DIR__ . '/UserBackend/');
    // });
});

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Portal | MangoSoft</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('/backend/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('/backend/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ asset('/backend/bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('/backend/dist/css/adminlte.min.css')}}">
</head>
<body class="hold-transition login-page">
  <div class="card" style="background-color: #ecf0f1;">
      <div class="card-header" style="text-align: center;">
        <h1 style="color: rgb(128, 0, 107); text-align: center;"><strong>I</strong>nventory <strong>M</strong>anagement <strong>S</strong>ystem</h1>
      </div>
      
      <!-- /.card-header -->
      <div class="card-body">
        <div class="col-md-12">
          {{-- @include('admin.backend.layouts.error') --}}
          @include('admin.backend.includes.messages')
        </div>
        
        <form action="{{ route('admin.login') }}" method="post">
            {{ csrf_field() }}
        
          <div class="row">
            <div class="col-md-5">
              <div class="input-group mb-3 ">
                
                <input type="email" class="form-control" name="email" placeholder="Email">
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="fa fa-user"></i>
                  </span>
                </div>
              </div>
              @if($errors->has('email'))
                            <div class="invalid-feedback">
                                {{ $errors->first('email') }}
                            </div>
                        @endif
            </div>

            <div class="col-md-5">
              <div class="input-group mb-3">
                
                <input type="password" class="form-control" name="password" placeholder="Password">
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="fa fa-lock"></i>
                  </span>
                </div>
              </div>
            </div>

            <div class="col-md-2">
              <div class="input-group mb-3">
              <button class="btn btn-success">Login</button>
              </div>  
            </div>
          </div>

          {{-- <div class="form-group row">
            <div class="col-md-5">
                <div class="form-check" style="padding-left: 0px;">
                    <input class="form-check-input" style="cursor: pointer;" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                    <label class="form-check-label offset-md-1" for="remember" style="margin: 3px 2em; cursor: pointer;">
                        {{ __('Remember Me') }}
                    </label>
                </div>
            </div>

            <div class="col-md-5">
              
              <a class="btn btn-link" href="{{ route('admin.password.request') }}">
                  {{ __('Forgot Your Password?') }}
              </a>
          </div>
        </div> --}}
        </form>
        
      </div>

      <!-- /.card-body --> 
  </div>
  <!-- /.card -->


<!-- jQuery 3 -->
<script src="{{ asset('/backend/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('/backend/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script>
  $(document).ready(function(){
    setTimeout(function(){
      $(".alert").remove();
    }, 5000 ); // 5 secs

  });
</script>
</body>
</html>