routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/drilldown', 'Admin\HomeController@drilldown')->name('dash');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

    //change password
    Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
    Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');
    
    // settings
    Route::resource('settings', 'Admin\SettingsController');
    // Route::group(['namespace' => 'Inventory'], function () {
        
        includeRouteFiles(__DIR__ . '/UserBackend/');
    // });
});

resources/views/admin/backend/layouts/error.blade.php
@if(count($errors) > 0)
    <div class="form-group">
        <div class="col-md-12">
            @foreach($errors->all() as $error)
                <p class="alert alert-danger">{{ $error}}</p>
            @endforeach   
        </div>    
    </div>
@endif

resources/views/admin/backend/layouts/footer.blade.php
<footer class="main-footer">
    
    <!-- <span>{{strip_tags(html_entity_decode($setting->copyright))}}</span> -->
    <span>@php echo $setting->copyright @endphp</span>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
</footer>

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('/backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('/backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{ asset('/backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{ asset('/backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{ asset('/backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{ asset('/backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('/backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<script src="{{ asset('/backend/plugins/moment/moment.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{ asset('/backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{ asset('/backend/plugins/datepicker/js/bootstrap-datepicker.min.js')}}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('/backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{ asset('/backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('/backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('/backend/dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('/backend/dist/js/demo.js')}}"></script>

<script src="{{ asset('/backend/js/select-all.js')}}"></script>
<script src="{{ asset('/backend/bower_components/select2/dist/js/select2.full.min.js')}}"></script>

<!-- dataTable -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.0/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.colVis.min.js"></script>


<script>
  $(document).ready(function(){
      setTimeout(function(){
         $(".alert").remove();
      }, 5000 ); // 5 secs
  
  });

  $(document).ready(function(){
      $('.select2').select2();
  });


          // yajradatatables 

    $(function() {
  let copyButtonTrans = '{{ trans('global.datatables.copy') }}'
  let csvButtonTrans = '{{ trans('global.datatables.csv') }}'
  let excelButtonTrans = '{{ trans('global.datatables.excel') }}'
  let pdfButtonTrans = '{{ trans('global.datatables.pdf') }}'
  let printButtonTrans = '{{ trans('global.datatables.print') }}'
  let colvisButtonTrans = '{{ trans('global.datatables.colvis') }}'
  let selectAllButtonTrans = '{{ trans('global.select_all') }}'
  let selectNoneButtonTrans = '{{ trans('global.deselect_all') }}'

  let languages = {
  'en': 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/English.json'
  };

  $.extend(true, $.fn.dataTable.Buttons.defaults.dom.button, { className: 'btn' })
  $.extend(true, $.fn.dataTable.defaults, {
  language: {
  url: languages['{{ app()->getLocale() }}']
  },
  columnDefs: [{
    orderable: false,
    className: 'select-checkbox',
    targets: 0
  }, {
    orderable: false,
    searchable: false,
    targets: -1
  }],
  select: {
  style:    'multi+shift',
  selector: 'td:first-child'
  },
  order: [],
  scrollX: true,
  pageLength: 100,
  dom: 'lBfrtip<"actions">',
  buttons: [
  {
    extend: 'selectAll',
    className: 'btn-primary',
    text: selectAllButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'selectNone',
    className: 'btn-primary',
    text: selectNoneButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'copy',
    className: 'btn-default',
    text: copyButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'csv',
    className: 'btn-default',
    text: csvButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'excel',
    className: 'btn-default',
    text: excelButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'pdf',
    className: 'btn-default',
    text: pdfButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'print',
    className: 'btn-default',
    text: printButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'colvis',
    className: 'btn-default',
    text: colvisButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  }
  ]
  });

  $.fn.dataTable.ext.classes.sPageButton = '';
  });

</script>

@yield('scripts')
@yield('after-scripts')

resources/views/admin/backend/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('admin.backend.layouts.head')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
  @include('admin.backend.layouts.nav')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    @include('admin.backend.layouts.sidebar')
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content" style="padding-top: 20px">
    <!-- Content Header (Page header) -->
    {{-- <div class="content-header">
      
    </div> --}}
    <!-- /.content-header -->
    <div class="col-lg-8">
      @include('admin.backend.includes.messages')
    </div>
      @section('content')
        @show
    <!-- /.content -->
    </section>
  </div>
  <!-- /.content-wrapper -->
  @include('admin.backend.layouts.footer')
</body>
</html>

resources/views/admin/backend/layouts/nav.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      {{-- <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('admin.dashboard')}}" class="nav-link">Home</a>
      </li> --}}
      
    </ul>

    <!-- SEARCH FORM -->
    {{-- <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form> --}}

    <!-- Right navbar links -->
    {{-- <ul class="navbar-nav ml-auto">
            
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul> --}}
  </nav>

resources/views/admin/backend/layouts/sidebar.blade.php
<!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ asset('/backend/dist/img/AdminLTELogo.png')}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
      <a href="{{ route('admin.dashboard')}}" class="d-block">{{Auth::user()->name}}</a>
      </div>
    </div>

    
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
      
        <li class="nav-item">
          <a href="{{ route('admin.dashboard')}}" class="nav-link {{ (request()->is('admin')) ? 'active' : '' }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p> <span> {{ trans('global.dashboard') }} </span></p>
          </a>
        </li>
        
            @can('user-management-access')
            <li class="nav-item has-treeview {{ request()->is('admin/permissions*') ? 'menu-open' : '' }} {{ request()->is('admin/roles*') ? 'menu-open' : '' }} {{ request()->is('admin/groups*') ? 'menu-open' : '' }} {{ request()->is('admin/users*') ? 'menu-open' : '' }}">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-users">

                    </i>
                    <p>
                        <span>{{ trans('cruds.userManagement.title') }}</span>
                        <i class="right fa fa-fw fa-angle-left" style="right:.5rem;"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="margin-left: 1rem;">
                    @can('permission-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-unlock-alt">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.permission.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                    @can('role-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-briefcase">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.role.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                    @can('group-access')
                      <li class="nav-item">
                          <a href="{{ route("admin.groups.index") }}" class="nav-link {{ request()->is('admin/groups') || request()->is('admin/groups/*') ? 'active' : '' }}">
                            <i class="fa fa-users"></i>
                              <p>
                                  <span>{{ trans('cruds.group.title') }}</span>
                              </p>
                          </a>
                      </li>
                    @endcan
                    @can('user-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-user">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.user.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan

        @can('supplier-management-access')
        <li class="nav-item has-treeview {{ request()->is('admin/suppliers_type*') ? 'menu-open' : '' }} {{ request()->is('admin/suppliers*') ? 'menu-open' : '' }} ">
          <a class="nav-link nav-dropdown-toggle" href="#">
              <i class="fa fa-ship">

              </i>
              <p>
                  <span>{{ trans('cruds.supplierManagement.title') }}</span>
                  <i class="right fa fa-fw fa-angle-left" style="right:.5rem;"></i>
              </p>
          </a>
          <ul class="nav nav-treeview" style="margin-left: 1rem;">
            @can('suppliertype-access')
                <li class="nav-item">
                  <a href="{{ route('admin.suppliers_type') }}" class="nav-link {{ request()->is('admin/suppliers_type') || request()->is('admin/suppliers_type/*') ? 'active' : '' }}">
                      <i class="fa fa-plus"></i>
                      <p> <span>{{ trans('menus.backend.sidebar.supplier_type') }}</span></p>
                  </a>
              </li>
            @endcan
            @can('suppliers-access')
              <li class="nav-item">
                  <a href="{{ route('admin.suppliers') }}" class="nav-link {{ request()->is('admin/suppliers') || request()->is('admin/suppliers/*') ? 'active' : '' }}">
                      <i class="fa fa-ship"></i>
                      <p> <span>{{ trans('menus.backend.sidebar.supplier') }}</span></p>
                  </a>
              </li>
            @endcan
          </ul>
        </li>
        @endcan

        @can('product-management-access')
        <li class="nav-item has-treeview {{ request()->is('admin/categories*') ? 'menu-open' : '' }} {{ request()->is('admin/products*') ? 'menu-open' : '' }} ">
          <a class="nav-link nav-dropdown-toggle" href="#">
              <i class="fa fa-plus-circle">

              </i>
              <p>
                  <span>{{ trans('cruds.productManagement.title') }}</span>
                  <i class="right fa fa-fw fa-angle-left" style="right:.5rem;"></i>
              </p>
          </a>
          <ul class="nav nav-treeview" style="margin-left: 1rem;">
            @can('category-access')
              <li class="nav-item">
                <a href="{{ route('admin.categories') }}" class="nav-link {{ request()->is('admin/categories') || request()->is('admin/categories/*') ? 'active' : '' }}">
                    <i class="fa fa-sitemap"></i>
                    <p> <span>{{ trans('menus.backend.sidebar.category') }}</span></p>
                </a>
              </li>
            @endcan
            @can('product-access')
              <li class="nav-item">
                  <a href="{{ route('admin.products') }}" class="nav-link {{ request()->is('admin/products') || request()->is('admin/products/*') ? 'active' : '' }}">
                          <i class="fa fa-plus-circle"></i>
                          <p> <span>{{ trans('menus.backend.sidebar.product') }}</span></p>
                  </a>
              </li>
            @endcan
          </ul>
        </li>
        @endcan

        @can('purchase-management-access')
        <li class="nav-item has-treeview {{ request()->is('admin/purchases*') ? 'menu-open' : '' }} {{ request()->is('admin/payments*') ? 'menu-open' : '' }} {{ request()->is('admin/receipts*') ? 'menu-open' : '' }} ">
            <a class="nav-link nav-dropdown-toggle" href="#">
                <i class="fa fa-cart-plus">

                </i>
                <p>
                    <span>{{ trans('cruds.purchaseManagement.title') }}</span>
                    <i class="right fa fa-fw fa-angle-left" style="right:.5rem;"></i>
                </p>
            </a>
            <ul class="nav nav-treeview" style="margin-left: 1rem;">
            @can('purchase-access')
              <li class="nav-item">
                  <a href="{{ route('admin.purchases') }}" class="nav-link {{ request()->is('admin/purchases') || request()->is('admin/purchases/*') ? 'active' : '' }}">
                      <i class="fa fa-cart-plus"></i>
                      <p> <span>{{ trans('menus.backend.sidebar.purchase') }}</span></p>
                  </a>
              </li>
            @endcan
            @can('payment-access')
              <li class="nav-item">
                <a href="{{ route('admin.payments') }}" class="nav-link {{ request()->is('admin/payments') || request()->is('admin/payments/*') ? 'active' : '' }}">
                    <i class="fa fa-credit-card"></i>
                    <p> <span>{{ trans('menus.backend.sidebar.payment') }}</span></p>
                </a>
              </li>
            @endcan
            @can('receipt-access')
              <li class="nav-item">
                <a href="{{ route("admin.receipts.allReceipts") }}" class="nav-link {{ request()->is('admin/receipts') || request()->is('admin/receipts/*') ? 'active' : '' }}">
                  <i class="far fa-money-bill-alt"></i>
                    <p>
                        <span>{{ trans('menus.backend.sidebar.receipt') }}</span>
                    </p>
                </a>
            </li>
            @endcan
            </ul>
        </li>
        @endcan

            @can('customer-access')
              <li class="nav-item">
                  <a href="{{ route('admin.customers') }}" class="nav-link {{ request()->is('admin/customers') || request()->is('admin/customers/*') ? 'active' : '' }}">
                      <i class="fa fa-user"></i>
                      <p> <span>{{ trans('menus.backend.sidebar.customer') }}</span></p>
                  </a>
              </li>
            @endcan

        @can('sale-management-access')
        <li class="nav-item has-treeview {{ request()->is('admin/sales*') ? 'menu-open' : '' }} {{ request()->is('admin/invoices*') ? 'menu-open' : '' }} {{ request()->is('admin/receives*') ? 'menu-open' : '' }} ">
            <a class="nav-link nav-dropdown-toggle" href="#">
                <i class="fa fa-money">

                </i>
                <p>
                    <span>{{ trans('cruds.saleManagement.title') }}</span>
                    <i class="right fa fa-fw fa-angle-left" style="right:.5rem;"></i>
                </p>
            </a>
            <ul class="nav nav-treeview" style="margin-left: 1rem;">
            @can('sale-access')
              <li class="nav-item">
                <a href="{{ route('admin.sales') }}" class="nav-link {{ request()->is('admin/sales') || request()->is('admin/sales/*') ? 'active' : '' }}">
                    <i class="fa fa-money"></i>
                    <p> <span>{{ trans('menus.backend.sidebar.sale') }}</span></p>
                </a>
              </li>
            @endcan
            @can('receive-access')
            <li class="nav-item">
              <a href="{{ route('admin.receives') }}" class="nav-link {{ request()->is('admin/receives') || request()->is('admin/receives/*') ? 'active' : '' }}">
                  <i class="fa fa-credit-card"></i>
                  <p> <span>{{ trans('menus.backend.sidebar.receive') }}</span></p>
              </a>
            </li>
          @endcan
          @can('invoice-access')
            <li class="nav-item">
              <a href="{{ route('admin.invoices.allInvoices') }}" class="nav-link {{ request()->is('admin/invoices') || request()->is('admin/invoices/*') ? 'active' : '' }}">
                <i class="far fa-money-bill-alt"></i>
                  <p>
                      <span>{{ trans('menus.backend.sidebar.invoice') }}</span>
                  </p>
              </a>
          </li>
          @endcan
          </ul>
      </li>
      @endcan

            <li class="nav-item">
                <a href="{{ route('admin.settings.create') }}" class="nav-link {{ request()->is('admin/settings') || request()->is('admin/settings/*') ? 'active' : '' }}">
                    <i class="fa fa-user"></i>
                    <p> <span>{{ trans('menus.backend.sidebar.setting') }}</span></p>
                </a>
            </li>

            <li class="nav-item">
              <a href="{{ route('admin.password.create') }}" class="nav-link {{ request()->is('admin/change-password') || request()->is('admin/change-password/*') ? 'active' : '' }}">
                  <i class="fa fa-key"></i>
                  <p> <span>{{ trans('global.change_password') }}</span></p>
              </a>
            </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>

  <div class="sidebar sidebar_footer" style="text-align:center;">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <li class="nav-item">
        <a href="{{route('admin.logout')}}" class="nav-link">
          <i class="nav-icon fas fa-sign-out-alt"></i>
            <p> <span>{{trans('global.logout')}}</span></p>
        </a>
      </li>
    </ul>
  </div>
  <!-- /.sidebar -->